load("@rules_python//python:py_library.bzl", "py_library")

py_library(
    name = "game_assets",
    srcs = glob(["**/*.py"]),
    data = glob(["**/*.txt"]),
    visibility = ["//:__subpackages__"],
    deps = [],
)
